services:
  # Backend Python (Flask) Service
  - type: web
    name: clio-backend
    env: python
    region: ohio
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - fromGroup: clio-secrets
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --chdir backend app:app"

  # Frontend Static Site
  - type: static
    name: clio-frontend
    region: ohio
    plan: free
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://clio-backend.onrender.com/api/$1
      - type: rewrite
        source: /*
        destination: /index.html

# Environment Variable Group for Secrets
envVarGroups:
  - name: clio-secrets
    envVars:
      - key: OPENAI_API_KEY
        value: "YOUR_KEY_HERE"