############
# SERVICES #
############

services:
  # -------------------  BACK-END  -------------------
  - type: web
    name: clio-backend
    runtime: python       # <- NEW: runtime replaces env
    plan: free            # starter/free/standard... free *is* valid for web
    branch: main          # optional – explicit is clearer
    healthCheckPath: /api/health

    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app \
                  --bind 0.0.0.0:$PORT --workers 1 --timeout 120

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: clipboard.db
      - fromGroup: clio-secrets

  # -------------------  FRONT-END  -------------------
  - type: web
    name: clio-frontend
    runtime: static       # <- tells Render "this is a static site"
    staticPublishPath: ./frontend

    # custom headers / rewrites are fine here
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000

##########################
# ENV-VAR GROUPS (SECRET)#
##########################
envVarGroups:
  - name: clio-secrets
    envVars:
      - key: OPENAI_API_KEY
        sync: false    # you'll paste it once in the dashboard