services:
  # Backend - Python/Flask API
  - type: web
    name: clio-backend
    env: python
    plan: free
    region: ohio
    healthCheckPath: /api/health
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --chdir backend app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - fromGroup: clio-secrets

  # Frontend - Static Site
  - type: static
    name: clio-frontend
    plan: free
    region: ohio
    staticPublishPath: ./frontend
    # Add rewrite rules to proxy API requests to the backend
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: http://clio-backend:10000/api/$1
      - type: rewrite
        source: /*
        destination: /index.html

# Environment Variable Group for Secrets
envVarGroups:
  - name: clio-secrets
    envVars:
      - key: OPENAI_API_KEY
        value: "YOUR_KEY_HERE" # User will paste this in Render dashboard