services:
  # Backend Python (Flask) Service
  - type: web
    name: clio-backend
    env: python
    region: ohio
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
      - fromGroup: clio-secrets
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --chdir backend app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"

  # Frontend Static Site
  - type: static
    name: clio-frontend
    region: ohio
    plan: free
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate"
      - path: /assets/*
        name: Cache-Control
        value: "public, max-age=31536000"

# Environment Variable Group for Secrets
envVarGroups:
  - name: clio-secrets
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # This will be set manually in Render dashboard