services:
  - type: web
    name: clio-backend
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production